### ISSUE TITLE
Trained Model Parameters 

### ISSUE THREAD

**Issue by firattamur** [fidler-lab/defgrid-release#1]
Hello,

Thank you for your great work and code. 
Could you please share your trained model parameters that you trained on the BSD500 dataset for superpixels?

Thank you

**Comment by SteveJunGao** [comment]
Hi,

Thanks for your interest in our work! We are still actively preparing the code and trained model on BSD500 dataset, it will be released soon, stay tuned! 

We appreciate your patience, Thanks!

Jun
