### ISSUE TITLE
cannot find gtFine images 

### ISSUE THREAD

**Issue by iszihan** [fidler-lab/defgrid-release#6]
Hello, there is another issue that the training script says cannot find '/media/selenaling/Elements/cityscapes/leftImg8bit_trainvaltest/gtFine/train/strasbourg/strasbourg_000001_014258_gtFine_labelIds.png', and it isn't straightforward to me how to generate this ground truth given the json files. Am wondering if there are instructions on this part? Thank you in advance.

**Comment by SteveJunGao** [comment]
This seems the dataset is not properly set, you can follow **data** section in the README to prepare the dataset and set the correct path for it
