### ISSUE TITLE
Help about interpolated sum function.

### ISSUE THREAD

**Issue by firattamur** [fidler-lab/defgrid-release#9]
Hello, 

I am trying to figure out how did you pass extracted features to grid points. I think [interpolated_sum](https://github.com/fidler-lab/defgrid-release/blob/6b57a79afa8818910abe1221ae119fae61463017/Models/GNN/superpixel_grid.py#L97) function is doing this but I have really hard time to understand your function. Could you provide some explanation about it or maybe a reference link to guide me. 

Thank you

**Comment by SteveJunGao** [comment]
Hi Thanks for your interests on our paper! the interpolated _sum is similar to the grid_sample function in pytorch, you can refer to here: https://pytorch.org/docs/stable/nn.functional.html?highlight=grid_sample#torch.nn.functional.grid_sample
